// Code generated by goctl. DO NOT EDIT.
// Source: inventory.proto

package inventoryclient

import (
	"context"

	"zero-mall/service/inventory_svc/types/inventory"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty       = inventory.Empty
	GoodsIdInfo = inventory.GoodsIdInfo
	SellInfo    = inventory.SellInfo

	Inventory interface {
		SetInv(ctx context.Context, in *GoodsIdInfo, opts ...grpc.CallOption) (*Empty, error)
		InvDetail(ctx context.Context, in *GoodsIdInfo, opts ...grpc.CallOption) (*GoodsIdInfo, error)
		Sell(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error)
		CallbackSell(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultInventory struct {
		cli zrpc.Client
	}
)

func NewInventory(cli zrpc.Client) Inventory {
	return &defaultInventory{
		cli: cli,
	}
}

func (m *defaultInventory) SetInv(ctx context.Context, in *GoodsIdInfo, opts ...grpc.CallOption) (*Empty, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.SetInv(ctx, in, opts...)
}

func (m *defaultInventory) InvDetail(ctx context.Context, in *GoodsIdInfo, opts ...grpc.CallOption) (*GoodsIdInfo, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.InvDetail(ctx, in, opts...)
}

func (m *defaultInventory) Sell(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.Sell(ctx, in, opts...)
}

func (m *defaultInventory) CallbackSell(ctx context.Context, in *SellInfo, opts ...grpc.CallOption) (*Empty, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.CallbackSell(ctx, in, opts...)
}
