// Code generated by goctl. DO NOT EDIT.
package types

type CreateRequest struct {
	Name       string `json:"name"`
	GoodsSn    string `json:"goodsSn"`
	GoodsBrief string `json:"goodsBrief"`
	ShopPrice  int64  `json:"shopPrice"`
	Status     int64  `json:"status"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type DetailRequest struct {
	Id int64 `path:"id":"id"`
}

type DetailResponse struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	GoodsSn    string `json:"goodsSn"`
	GoodsBrief string `json:"goodsBrief"`
	ShopPrice  int64  `json:"shopPrice"`
	Status     int64  `json:"status"`
}

type RemoveRequest struct {
	Id int64 `path:"id":"id"`
}

type RemoveResponse struct {
}

type UpdateRequest struct {
	Id         int64  `json:"id"`
	Name       string `json:"name,optional"`
	GoodsSn    string `json:"goodsSn,optional"`
	GoodsBrief string `json:"goodsBrief,optional"`
	ShopPrice  int64  `json:"shopPrice,optional"`
	Status     int64  `json:"status,optional"`
}

type UpdateResponse struct {
}
