// Code generated by goctl. DO NOT EDIT.
// Source: inventory.proto

package server

import (
	"context"

	"zero-mall/service/inventory_svc/internal/logic"
	"zero-mall/service/inventory_svc/internal/svc"
	"zero-mall/service/inventory_svc/types/inventory"
)

type InventoryServer struct {
	svcCtx *svc.ServiceContext
	inventory.UnimplementedInventoryServer
}

func NewInventoryServer(svcCtx *svc.ServiceContext) *InventoryServer {
	return &InventoryServer{
		svcCtx: svcCtx,
	}
}

func (s *InventoryServer) SetInv(ctx context.Context, in *inventory.GoodsIdInfo) (*inventory.Empty, error) {
	l := logic.NewSetInvLogic(ctx, s.svcCtx)
	return l.SetInv(in)
}

func (s *InventoryServer) InvDetail(ctx context.Context, in *inventory.GoodsIdInfo) (*inventory.GoodsIdInfo, error) {
	l := logic.NewInvDetailLogic(ctx, s.svcCtx)
	return l.InvDetail(in)
}

func (s *InventoryServer) Sell(ctx context.Context, in *inventory.SellInfo) (*inventory.Empty, error) {
	l := logic.NewSellLogic(ctx, s.svcCtx)
	return l.Sell(in)
}

func (s *InventoryServer) CallbackSell(ctx context.Context, in *inventory.SellInfo) (*inventory.Empty, error) {
	l := logic.NewCallbackSellLogic(ctx, s.svcCtx)
	return l.CallbackSell(in)
}
