// Code generated by goctl. DO NOT EDIT.
// Source: shopcar.proto

package server

import (
	"context"

	"zero-mall/service/shopcar_svr/internal/logic"
	"zero-mall/service/shopcar_svr/internal/svc"
	"zero-mall/service/shopcar_svr/types/shopCar"
)

type ShopCarServer struct {
	svcCtx *svc.ServiceContext
	shopCar.UnimplementedShopCarServer
}

func NewShopCarServer(svcCtx *svc.ServiceContext) *ShopCarServer {
	return &ShopCarServer{
		svcCtx: svcCtx,
	}
}

// 添加商品到购物车
func (s *ShopCarServer) AddGoodsToCar(ctx context.Context, in *shopCar.ShopCarItemInfo) (*shopCar.ShopCarItemInfo, error) {
	l := logic.NewAddGoodsToCarLogic(ctx, s.svcCtx)
	return l.AddGoodsToCar(in)
}

// 修改购物车商品数量和选中状态
func (s *ShopCarServer) UpdateGoodsToCar(ctx context.Context, in *shopCar.ShopCarItemInfo) (*shopCar.Empty, error) {
	l := logic.NewUpdateGoodsToCarLogic(ctx, s.svcCtx)
	return l.UpdateGoodsToCar(in)
}

// 删除购物车中的商品
func (s *ShopCarServer) DeleteGoodsToCar(ctx context.Context, in *shopCar.ShopCarItemInfo) (*shopCar.Empty, error) {
	l := logic.NewDeleteGoodsToCarLogic(ctx, s.svcCtx)
	return l.DeleteGoodsToCar(in)
}

// 获取购物车中的商品 传用户id获取用户的购物车商品，+传checked获取购物车选中商品
func (s *ShopCarServer) GetShopCarList(ctx context.Context, in *shopCar.ShopCarItemInfo) (*shopCar.ShopCarListResponse, error) {
	l := logic.NewGetShopCarListLogic(ctx, s.svcCtx)
	return l.GetShopCarList(in)
}

// 批量删除购物车的商品
func (s *ShopCarServer) BatchDelShopCar(ctx context.Context, in *shopCar.ShopCarListRequest) (*shopCar.Empty, error) {
	l := logic.NewBatchDelShopCarLogic(ctx, s.svcCtx)
	return l.BatchDelShopCar(in)
}

// 回滚
func (s *ShopCarServer) RollBackDelShopCar(ctx context.Context, in *shopCar.ShopCarListRequest) (*shopCar.Empty, error) {
	l := logic.NewRollBackDelShopCarLogic(ctx, s.svcCtx)
	return l.RollBackDelShopCar(in)
}
